package Server;
public enum ResponseOrErrorType {
    SUCCESSFUL,
    DUPLICATE_USERNAME,
    DUPLICATE_ACCOUNTNAME,
    DUPLICATE_EMAIL,
    INVALID_EMAILFORMAT,
    DUPLICATE_PHONENUMBER,
    USER_NOTFOUND,
    INVALID_PASS,


}
