public enum ResponseOrErrorType {
    SUCCESSFUL,
    DUPLICATE_USERNAME,
    DUPLICATE_ACCOUNTNAME,
    DUPLICATE_EMAIL,
    INVALID_EMAIL,
    INVALID_DATEFORMAT,
    INVALID_EMAILFORMAT,
    DUPLICATE_PHONENUMBER,
    USER_NOTFOUND,
    INVALID_PASS,
    NOT_EQUALPASSANDREPITITION,
    ALREADY_EXISTS,
    LOWERCASE,
    UPPERCASE,
    UNSUCCESSFUL,

}
