public enum Api {
    TYPE_SIGNUP ,
    TYPE_SIGNIN ,
    TYPE_CHANGE_PROF ,
    TYPE_Update_PROF ,
    TYPE_USER_SEARCH ,
    TYPE_USER_LEFT ,
    TYPE_ADD_TWEET ,
    TYPE_MESSAGE,
    TYPE_WRITING_TWEET,
    TYPE_ADDING_USER_TO_FILE,
    TYPE_LOADING_TIMELINE,
}
